### ISSUE TITLE
Excercise part-2 country app's api linked changed

### ISSUE THREAD

**Issue by zakariamahmud1** [kayraberktuncer/fullstackopen#25]
The new api link is: https://restcountries.com/v3.1/all and because of that the application is breaking and I am getting this error: Uncaught TypeError: country.name.toLowerCase is not a function while filtering the country name. I would highly appreciate if you could fix the issue. Thanks in advance.

**Comment by k61b** [comment]
Hello @zakariamahmud1,

While creating the project, I had developed it in accordance with the needs of that time. If you want to fix it you can open a pr.

Thanks.
